### ISSUE TITLE
Explain Transactions

### ISSUE THREAD

**Issue by xaprb** [VividCortex/go-database-sql-tutorial#37]
A user was creating a transaction but then accessing the DB, and didn't realize that those statements weren't inside the transaction.

The other helpful property of transactions is to bind statements to a single connection, for things like session state, user-defined variables, temporary tables, etc. We could illustrate this.

**Comment by jonathaningram** [comment]
@xaprb do you mean that in this imaginary code:

``` go
tx, err := db.Begin()
if err != nil {
    panic(err)
}

user := User{}
err = db.QueryRow(`select id from "users" where id = $1`, id).Scan(&user.ID)
if err == sql.ErrNoRows {
    return
} else if err != nil {
    panic(err)
}

if _, err := db.Exec(
    `update "users" set name = $2 where id = $1`,
    u.ID,
    u.Name,
); err != nil {
    panic(err)
}

if err := tx.Commit(); err != nil {
    panic(err)
}

```

that the user may be thinking that the `SELECT` and `UPDATE` statements are happening in the transaction, but in fact they are not since they act on `db` not `tx`?

Incidentally, I had some code like this that did a `SELECT/UPDATE` as above without any begin/commit (however the update was conditional so it was only executed once depending on the value of a column from the select - think of a counter recording an action - if the action has already been done once we don't want to increment the counter again).

But that code won't play nicely when it's executed concurrently in many goroutines because some routines may both execute the `SELECT` before any `UPDATE` is done and think that an increment is required and both may then increment the counter, which is wrong and you end up with a bigger counter than the actual number of times the action happened.

Anyway, adding begin/commit around that code, but NOT calling `QueryRow` or `Exec` from the `tx` transaction fixed the concurrency problem for me - the counter was never incremented more than it should have been.

However, introducing this begin/commit code resulted in seeing the old error `driver: bad connection` on both the `db.Begin()` call and the `db.QueryRow()` call so there may be some issue with my code (maybe it would work fine if I called those funcs on `tx`) and there's potentially some room for explanation in the SQL tutorial about this.

**Comment by xaprb** [comment]
> that the user may be thinking that the SELECT and UPDATE statements are happening in the transaction, but in fact they are not since they act on db not tx?

Exactly!

> However, introducing this begin/commit code resulted in seeing the old error driver: bad connection on both the db.Begin() call and the db.QueryRow()

Hm, I don't have any experiences with that.
